SELECT
    PG.IDPRODUTO,
    PG.IDSUBPRODUTO,
    PG.DESCRRESPRODUTO,
    PR.IDSECAO,
    S.DESCRSECAO,

    PVF.FABRICANTE,
    PVF.IDCODBARPROD AS CODBARRAS,

    PF1.CODIGOINTERNOFORN,

    CBX.CODBARCX AS CODBARRAS_CAIXA,

    PR.FLAGATIVO

FROM DBA.PRODUTO_GRADE PG

JOIN DBA.PRODUTO PR
  ON PR.IDPRODUTO = PG.IDPRODUTO

LEFT JOIN DBA.SECAO S
  ON S.IDSECAO = PR.IDSECAO

LEFT JOIN DBA.PRODUTOS_VIEW PVF
  ON PVF.IDSUBPRODUTO = PG.IDSUBPRODUTO

LEFT JOIN LATERAL (
    SELECT RTRIM(PF.CODIGOINTERNOFORN) AS CODIGOINTERNOFORN
    FROM DBA.PRODUTO_FORNECEDOR PF
    WHERE PF.IDPRODUTO    = PG.IDPRODUTO
      AND PF.IDSUBPRODUTO = PG.IDSUBPRODUTO
    ORDER BY PF.IDCLIFOR
    FETCH FIRST 1 ROW ONLY
) PF1 ON 1=1

LEFT JOIN LATERAL (
    SELECT
        CASE
            WHEN TRIM(COALESCE(PGCX.CODBARCX, '')) = '' THEN VARCHAR(PGCX.IDCODBARCX)
            ELSE PGCX.CODBARCX
        END AS CODBARCX
    FROM DBA.PRODUTO_GRADE_CODBARCX PGCX
    WHERE PGCX.IDPRODUTO    = PG.IDPRODUTO
      AND PGCX.IDSUBPRODUTO = PG.IDSUBPRODUTO
    ORDER BY
        COALESCE(PGCX.QTDMULTIPLA, 0) DESC,
        COALESCE(PGCX.DTALTERACAO, TIMESTAMP('1900-01-01-00.00.00')) DESC
    FETCH FIRST 1 ROW ONLY
) CBX ON 1=1

WHERE PR.FLAGATIVO = 'T'

ORDER BY PR.IDSECAO, PG.DESCRRESPRODUTO

FOR READ ONLY;
