SELECT
    DADOS.IDCLIFOR,
    FORN.NOME AS DESCLIENTE,  -- Razão social do fornecedor

    DADOS.IDPRODUTO,
    DADOS.IDSUBPRODUTO,

    DADOS.IDSECAO,
    DADOS.DESCRSECAO,

    DADOS.IDGRUPO,
    DADOS.DESCRGRUPO,

    DADOS.IDSUBGRUPO,
    DADOS.DESCRSUBGRUPO,

    DADOS.CODBARRAS,
    DADOS.CODIGOINTERNOFORN,

    DADOS.DESCRRESPRODUTO,
    DADOS.DESCRICAOPRODUTO,

    DADOS.MODELO,
    DADOS.FABRICANTE,

    DADOS.EMBALAGEMENTRADA,
    DADOS.VALGRAMAENTRADA,
    DADOS.EMBALAGEMSAIDA,

    DADOS.DTCADASTRO,
    DADOS.DTULTIMACOMPRA,
    DADOS.EMPRESA_ESTOQUE,
    DADOS.CUSTOULTIMACOMPRA,

    (
        SELECT
            COALESCE(
                CASE
                    WHEN DADOS.VALGRAMAENTRADA = 1000 THEN
                        DECIMAL(FLOAT(SUM(ESA.QTDATUALESTOQUE)) / 1000, 15, 2)
                    WHEN DADOS.VALGRAMAENTRADA IS NOT NULL AND DADOS.VALGRAMAENTRADA > 0 THEN
                        DECIMAL(FLOAT(SUM(ESA.QTDATUALESTOQUE)) / FLOAT(DADOS.VALGRAMAENTRADA), 15, 2)
                    ELSE
                        SUM(ESA.QTDATUALESTOQUE)
                END,
                0
            )
        FROM DBA.ESTOQUE_SALDO_ATUAL ESA
        WHERE  ESA.IDEMPRESA      = DADOS.EMPRESA_ESTOQUE
           AND ESA.IDPRODUTO      = DADOS.IDPRODUTO
           AND ESA.IDSUBPRODUTO   = DADOS.IDSUBPRODUTO
           AND ESA.IDLOCALESTOQUE = 1
    ) AS QTDATUALESTOQUE

FROM DBA.CLIENTE_FORNECEDOR FORN

JOIN (
    SELECT *
    FROM (
        SELECT
            PV.IDPRODUTO,
            PV.IDSUBPRODUTO,

            PF.IDCLIFOR,
            RTRIM(PF.CODIGOINTERNOFORN) AS CODIGOINTERNOFORN,

            PV.IDSECAO,
            S.DESCRSECAO,

            PV.IDGRUPO,
            G.DESCRGRUPO,

            PV.IDSUBGRUPO,
            SG.DESCRSUBGRUPO,

            PV.IDCODBARPROD AS CODBARRAS,

            PV.DESCRRESPRODUTO,
            PV.DESCRICAOPRODUTO,

            RTRIM(PV.MODELO)     AS MODELO,
            RTRIM(PV.FABRICANTE) AS FABRICANTE,

            PV.EMBALAGEMENTRADA,
            PV.VALGRAMAENTRADA,
            PV.EMBALAGEMSAIDA,

            PV.DTCADASTRO,
            PPP.DTULTIMACOMPRA,

            PPP.IDEMPRESA AS EMPRESA_ESTOQUE,
            PPP.CUSTOULTIMACOMPRA,

            ROW_NUMBER() OVER (
                PARTITION BY PV.IDPRODUTO
                ORDER BY PPP.DTULTIMACOMPRA DESC
            ) AS RN

        FROM DBA.PRODUTOS_VIEW PV
        JOIN DBA.SECAO    S  ON PV.IDSECAO    = S.IDSECAO
        JOIN DBA.GRUPO    G  ON PV.IDGRUPO    = G.IDGRUPO
        JOIN DBA.SUBGRUPO SG ON PV.IDSUBGRUPO = SG.IDSUBGRUPO

        JOIN DBA.POLITICA_PRECO_PRODUTO PPP
             ON  PV.IDPRODUTO    = PPP.IDPRODUTO
             AND PV.IDSUBPRODUTO = PPP.IDSUBPRODUTO
             AND PPP.IDEMPRESA IN (1, 3)

        JOIN DBA.PRODUTO_FORNECEDOR PF
             ON  PV.IDPRODUTO    = PF.IDPRODUTO
             AND PV.IDSUBPRODUTO = PF.IDSUBPRODUTO

        WHERE UPPER(PV.FLAGINATIVO) = 'F'
    ) TMP
    WHERE RN = 1
) AS DADOS
  ON FORN.IDCLIFOR = DADOS.IDCLIFOR

WHERE SUBSTR(FORN.CNPJCPF, 1, 8) <> '15145444'
FOR READ ONLY;
